# Generated by Django 5.2.5 on 2025-09-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contrasena_acceso',
            field=models.CharField(default='contraseña_temporal', max_length=128),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_acceso',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
