# Generated by Django 5.2.5 on 2025-09-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_contrasena_acceso_cliente_usuario_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena_acceso',
            field=models.CharField(max_length=128),
        ),
    ]
